//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Filter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Generic.Filter.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error filter type {0} doesn&apos;t contain any criteria.
        /// </summary>
        internal static string ErrorFilterDoesNotContainAnyCriteria {
            get {
                return ResourceManager.GetString("ErrorFilterDoesNotContainAnyCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid member type. Member {0} should have type {1} but has {2}.
        /// </summary>
        internal static string ErrorInvalidMemberType {
            get {
                return ResourceManager.GetString("ErrorInvalidMemberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression &apos;{0}&apos; must resolve to top-level member and not any child object&apos;s properties. You can use ForPath instead..
        /// </summary>
        internal static string ErrorInvalidPropertyExpression {
            get {
                return ResourceManager.GetString("ErrorInvalidPropertyExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression &apos;{0}&apos; must resolve to object&apos;s member path chain..
        /// </summary>
        internal static string ErrorInvalidPropertyPathExpression {
            get {
                return ResourceManager.GetString("ErrorInvalidPropertyPathExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not use {0} expression of type {1} for path property mapping.
        /// </summary>
        internal static string ErrorUnsupportedLambdaExpressionBodyForPathPropertyMapping {
            get {
                return ResourceManager.GetString("ErrorUnsupportedLambdaExpressionBodyForPathPropertyMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input MemberInfo must be if type EventInfo, FieldInfo, MethodInfo, or PropertyInfo.
        /// </summary>
        internal static string ErrorUnsupportedMemberInfoType {
            get {
                return ResourceManager.GetString("ErrorUnsupportedMemberInfoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not use {0} expression for property mapping. Invalid expression type..
        /// </summary>
        internal static string ErrorUnsupportedMemberTypeForMapping {
            get {
                return ResourceManager.GetString("ErrorUnsupportedMemberTypeForMapping", resourceCulture);
            }
        }
    }
}
